services:
  web:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ${BACKEND_PATH}:/var/www/html
    ports:
      - "80:80"
    configs:
      - source: apache_config
        target: /etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ${FRONTEND_PATH}:/app
    depends_on:
      - db
      - web
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pgdata:
    driver: local
  redis-data:
    driver: local
configs:
  apache_config:
    file: ${APACHE_CONFIG_PATH}
