import { Injectable } from '@angular/core';
import { CLOSED, IN_PROGRESS, Issue, OPEN, TO_DO } from '../../model/Issue';
import { UserService } from '../user/user.service';
import { User } from '../../model/User';

@Injectable({
    providedIn: 'root',
})
export class IssueService {
    constructor(private userService: UserService) {}

    getIssues(): Array<Issue> {
        const user = this.userService.getUser();
        return [
            {
                id: 1,
                title: 'Issue 1',
                description: 'Description for Issue 1',
                status: OPEN,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'IBM IT',
            },
            {
                id: 2,
                title: 'Issue 2',
                description: 'Description for Issue 2',
                status: TO_DO,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'IBM IT',
            },
            {
                id: 3,
                title: 'Issue 3',
                description: 'Description for Issue 3',
                status: CLOSED,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google IT',
            },

            {
                id: 4,
                title: 'Issue 4',
                description: 'Description for Issue 4',
                status: IN_PROGRESS,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google HR',
            },
            {
                id: 5,
                title: 'Issue 5',
                description: 'Description for Issue 5',
                status: CLOSED,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google IT',
            },

            {
                id: 6,
                title: 'Issue 6',
                description: 'Description for Issue 6',
                status: IN_PROGRESS,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google HR',
            },
            {
                id: 7,
                title: 'Issue 7',
                description: 'Description for Issue 7',
                status: CLOSED,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google IT',
            },

            {
                id: 8,
                title: 'Issue 8',
                description: 'Description for Issue 8',
                status: CLOSED,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google HR',
            },
            {
                id: 9,
                title: 'Issue 9',
                description: 'Description for Issue 9',
                status: OPEN,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google IT',
            },

            {
                id: 10,
                title: 'Issue 10',
                description: 'Description for Issue 10',
                status: IN_PROGRESS,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google HR',
            },
            {
                id: 11,
                title: 'Issue 11',
                description: 'Description for Issue 11',
                status: CLOSED,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google IT',
            },

            {
                id: 12,
                title: 'Issue 12',
                description: 'Description for Issue 12',
                status: IN_PROGRESS,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google HR',
            },
            {
                id: 13,
                title: 'Issue 13',
                description: 'Description for Issue 13',
                status: CLOSED,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google IT',
            },

            {
                id: 14,
                title: 'Issue 14',
                description: 'Description for Issue 14',
                status: CLOSED,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google HR',
            },
            {
                id: 15,
                title: 'Issue 15',
                description: 'Description for Issue 15',
                status: CLOSED,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google IT',
            },

            {
                id: 16,
                title: 'Issue 16',
                description: 'Description for Issue 16',
                status: IN_PROGRESS,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google HR',
            },
            {
                id: 17,
                title: 'Issue 17',
                description: 'Description for Issue 17',
                status: TO_DO,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google IT',
            },

            {
                id: 18,
                title: 'Issue 18',
                description: 'Description for Issue 18',
                status: TO_DO,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google HR',
            },
            {
                id: 19,
                title: 'Issue 19',
                description: 'Description for Issue 19',
                status: CLOSED,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google IT',
            },

            {
                id: 20,
                title: 'Issue 20',
                description: 'Description for Issue 20',
                status: CLOSED,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google HR',
            },
            {
                id: 21,
                title: 'Issue 21',
                description: 'Description for Issue 21',
                status: TO_DO,
                author: user as User,
                assignee: user as User,
                createdAt: new Date(),
                project: 'Google HR',
            },

            {
                id: 22,
                title: 'Issue 22',
                description: 'Description for Issue 22',
                status: IN_PROGRESS,
                author: user as User,
                assignee: null,
                createdAt: new Date(),
                project: 'Google Business',
            },
        ];
    }
}
